### ISSUE TITLE
2.6 ?

### ISSUE THREAD

**Issue by Picrrr** [symfony/orm-pack#11]
https://github.com/doctrine/doctrine2

refer to the 2.6 branch for the current stable

**Comment by mochalovserge** [comment]
great! they started use php 7.4 it's version don't use in production eat! very professional. my project is down. my work was stopped. thanks a lot.

**Comment by nicolas-grekas** [comment]
2.6 is allowed by the contraint (`^2.5.11` allows 2.6)
