### ISSUE TITLE
Wrong dependency

### ISSUE THREAD

**Issue by wirwolf** [symfony/orm-pack#17]
In my microservice project, we have so many problems with this fix. This package update by minor version from 1.0.6 to 1.0.7 and doctrine upgrade to from 1 to 2 version, and we have an error exception.

Related PR 
#13 
#16

Please  use semantic versioning(https://semver.org/)

**Comment by nicolas-grekas** [comment]
You should run `composer unpack orm` if you want to get precise control over your deps.
There's nothing else we can do about it here.
