### ISSUE TITLE
Abandoned packets

### ISSUE THREAD

**Issue by ahmetilhann** [symfony/orm-pack#23]
It gives warning when i create new project and install the orm package.

`Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.`
`Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.`

<img width="894" alt="Screen Shot 2020-02-29 at 16 34 51" src="https://user-images.githubusercontent.com/5680957/75608571-acce6300-5b11-11ea-840c-6b411caa9c0f.png">

**Comment by nicolas-grekas** [comment]
Yep, nothing we can do about here.
