### ISSUE TITLE
v1.0.8 embed doctrine/doctrine-migrations-bundle 2.x to 3.x which is not smooth upgrade

### ISSUE THREAD

**Issue by meshenka** [symfony/orm-pack#26]
doctrine/doctrine-migrations-bundle  2.1.2 => 3.0.1
doctrine/migrations 2.2.1 => 3.0.1

the composer update breaks lots of things that depend on those packages

**Comment by meshenka** [comment]
see #25

**Comment by nicolas-grekas** [comment]
See  symfony/flex#645
