### ISSUE TITLE
Change dependency version from "*" to hardcode

### ISSUE THREAD

**Issue by wirwolf** [symfony/orm-pack#34]
After run command composer update, composer change doctrine to new (major bc break ) version. In my composer.json orm-pack is hardcode version.

![image](https://user-images.githubusercontent.com/8457572/109012882-2e23eb80-76bb-11eb-965a-5d564d29c1e3.png)
Related 
#17 
#18

**Comment by nicolas-grekas** [comment]
unpack the pack
that's now done automatically for newly installed packs (update flex of course)
