### ISSUE TITLE
Symfony 6.4 SQLite DB error SQLitePlatform::getCreateDatabaseSQL caused by doctrine/dbal 4.0

### ISSUE THREAD

**Issue by avinsol** [symfony/orm-pack#42]
Hi, 
I installed a fresh symfony/skeleton:"6.4.*" project for an api app, then I required symfony/orm-pack and set the database in .env file as sqlite:
DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"

On executing the command console doctrine:database:create it throws the error:
`Could not create database /home/user/skeleton-api/var/data.db for connection named default
Operation "Doctrine\DBAL\Platforms\SQLitePlatform::getCreateDatabaseSQL" is not supported by platform.
`
After a lot of test and research I found that the doctrine/orm requires the doctrine/dbal version 4.0.0 and it seems nowadays it may be on development state without sqlite support or something similar, in fact at the doctrine website says that this version is not released yet.

Well, to solve this I made the following steps:
- composer require symfony/orm-pack --no-install     
- rm composer.lock
- edit composer.json and force to install doctrine/dbal 3.8.1 before doctrine/orm:
    "require": {
...
        **"doctrine/dbal": "3.8.1",**
        "doctrine/orm": "^3.0",
..
    },
- composer install  // to install from the composer.json file

After that the console doctrine:database:create runs well with no error and the database is created.
I don't know whether I will have more problems from here, but I liked to share my experience if any one has the same issue.
Also, it will be good if someone can modify the doctrine/orm dependencies to <4.0 version of doctrine/dbal while it is not stable version with sqlite support, it will be fully appreciate.
Thanks for your work.
Avinsol.

**Comment by derrabus** [comment]
> On executing the command console doctrine:database:create

Why would you do that on an SQLite database?

**Comment by derrabus** [comment]
Either way, I think we can close this issue.

The command is part of https://github.com/doctrine/DoctrineBundle. Please open an issue there if you want to discuss it further.

**Comment by olberger** [comment]
FWIW, I encountered this error while upgrading a project from 6.3 to 6.4, and figured out that my composer.json lacked a rule that seems to be now by default when creating a LTS project with `symfony new --version=lts`:
```
"doctrine/dbal": "^3",
```

Hope this helps,
