### ISSUE TITLE
Conflit with symfony/console version from symfony/flex

### ISSUE THREAD

**Issue by Babacooll** [symfony/orm-pack#6]
Hi,

Since this package requires symfony/orm 2.5.11 which requires symfony/console ~2.5|~3.0 this package seems not compatible with the new symfony/flex that requires symfony/console 4.0.

Or maybe I'm doing something wrong.

Thanks !

**Comment by janit** [comment]
I see this also, in the master branch of Doctrine the dependency is already set to `"symfony/console": "~3.0|~4.0"`, so I guess it's a matter of time (2.6.0?) that this will be updated.

I did make a PR for allowing console 4.0 as well, but I'm not sure if it's ok for them. You can follow progress here: https://github.com/doctrine/doctrine2/pull/6785

**Comment by fabpot** [comment]
Show your support here doctrine/doctrine2#6733. Closing this issue as there is unfortunately nothing we can do on our side.
