### ISSUE TITLE
Remove DoctrineMigrationsBundle

### ISSUE THREAD

**Issue by garak** [symfony/orm-pack#9]
I just updated and got DoctrineMigrationsBundle, along with a lot of things that simply I don't need.
Why bloating this pack? Can't we just leave it with minimal requirements?

**Comment by fabpot** [comment]
see #8

**Comment by weaverryan** [comment]
Just saw this issue, I'll re-post my comment here:

You can of course still install `doctrine/orm` and `doctrine/doctrine-bundle` independently if you want more control over your deps :). The goal with the packs is to package things together that cover the 90% use-case.

**Comment by afoeder** [comment]
can we close this please? Discussed and decided in #8 already.
